/**
 * This script was generated by Loon to simulate http requests.
 */

let url = "https://api.revenuecat.com/v1/subscribers/$RCAnonymousID%3A751e7f67194c4147bdbad97b69e6c2ee";
let headers = {
    'accept':'*/*',
    'x-observer-mode-enabled':'false',
    'x-client-build-version':'52',
    'x-is-sandbox':'false',
    'x-version':'4.31.5',
    'x-platform-flavor':'native',
    'accept-language':'en-US,en;q=0.9',
    'authorization':'Bearer GbFlYEUeaBtbuCHJOdWNcKFovqBUInoe',
    'content-type':'application/json',
    'user-agent':'Incognito/52 CFNetwork/1494.0.7 Darwin/23.4.0',
    'accept-encoding':'gzip, deflate, br',
    'x-apple-device-identifier':'F66C8881-B43C-4CC9-8567-FE7D43A33358',
    'x-rc-last-refresh-time':'1715232787000',
    'x-storefront':'TUR',
    'x-client-bundle-id':'com.overdesigned.ShareBear',
    'x-platform':'iOS',
    'x-platform-version':'Version 17.4.1 (Build 21E236)',
    'x-client-version':'1.0.15',
    'x-storekit2-enabled':'false',
};

let params = {
    url:url,
    timeout:5000,
    headers:headers,
};

$httpClient.get(params, function(errormsg,response,data) {
    if (errormsg) {
        console.log(errormsg);
    } else {
        console.log("Response Status: " + response.status);
        console.log("Response Headers: " + JSON.stringify(response.headers));
        console.log("Response Body: " + data);
    }
    $done();
});